apiVersion: v1
kind: Secret

metadata:
  name: cloudstream-secret
  namespace: cloudstream

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SECRET_KEY: your_super_secret_key
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123